version: '3.2'

services:
  node-api-swagger-boilerplate:
    image: node-api-swagger-boilerplate
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 dist/server.js